name: The Class Notes
tagline: Cornell University's Original Co-Ed A Cappella Group
email: classnotes@cornell.edu
url: http://theclassnotes.com

description: "The Class Notes is Cornell University's original co-ed a cappella group. Founded in 1983, The Class Notes performs a varied repertoire of contemporary Pop, R&B, Rock and Hip-hop songs. Each semester, the group performs in Call Auditorium for an audience of hundreds of fellow students."
keywords:
  - cornell
  - cornell a cappella
  - cornell class notes
  - co-ed a cappella

emails:
  general: classnotes@cornell.edu
  gm: gm@theclassnotes.com
  md: md@theclassnotes.com
  pres: president@theclassnotes.com

links:
  general_email: "[classnotes@cornell.edu](mailto:classnotes@cornell.edu)"
  gm_email: "[gm@theclassnotes.com](mailto:gm@theclassnotes.com)"
  md_email: "[md@theclassnotes.com](mailto:md@theclassnotes.com)"
  pres_email: "[president@theclassnotes.com](mailto:president@theclassnotes.com)"

permalink: "/:year/:month/:day/:title/"
markdown: redcarpet
relative_permalinks: false

twitter:
  name: theclassnotes
  link: http://twitter.com/theclassnotes
facebook:
  name: theclassnotes
  link: http://facebook.com/theclassnotes
youtube:
  name: cornellclassnotes
  link: http://youtube.com/cornellclassnotes

exclude:
  - 'Guardfile'
  - 'Gemfile*'
  - '.gitignore'
  - 'Rakefile'
  - 'README.markdown'
  - 'vendor'
  - '.sass-cache'
