#! /bin/bash

set -e

echo 'compiling SCSS...'
bundle exec compass compile -c ./_sass/config.rb
echo

echo 'compiling the jekyll site...'
bundle exec jekyll build --trace
echo

bundle exec ruby -e "require 'html/proofer';HTML::Proofer.new('./_site').run"

echo 'success'
